"""
telemetry_model.py

The telemetry-generation model (server fleet definition, the daily load curve, the
per-server baseline distributions, and the rule-based status label) shared between:

- generate_telemetry.py -- the one-shot batch generator that builds the fixed 7-day
  historical dataset the rest of this project (Bronze/Silver/Gold, the analysis
  notebook, the ML model) is built and evaluated against.
- ingestion/live_ingest.py -- the continuous mode that generates one fresh tick per
  server, on an interval, and uploads it directly (see that module's docstring for why
  continuous ingestion is a separate script rather than a mode of generate_telemetry.py).

Pulling this out into its own module means both paths draw from the exact same
distributions -- a "live" reading and a "historical" reading of the same server at the
same time of day look the same, because they're generated by the same code, not by two
copies that will inevitably drift as one gets edited and the other doesn't.

`generate_baseline` takes `rng` as an explicit parameter (rather than reading a module-
level global, which is what the original single-file version did) specifically so the
batch generator can pass its seeded, reproducible RNG while the live generator passes
an unseeded one -- each caller controls its own randomness rather than this module
deciding for them.
"""

import numpy as np
import pandas as pd


def build_servers(num_servers: int) -> list:
    """The server fleet definition: 10 servers, same metadata pattern used throughout
    the project (matches SERVER_METADATA in database/load_to_postgres.py)."""
    return [
        {"server_id": f"server{str(i).zfill(2)}", "hostname": f"web-app-{str(i).zfill(2)}",
         "environment": "production", "operating_system": "Ubuntu 22.04",
         "application": "order-processing-api"}
        for i in range(1, num_servers + 1)
    ]


def diurnal_multiplier(timestamps: pd.DatetimeIndex) -> np.ndarray:
    """
    Returns a multiplier (roughly 0.6 - 1.3) that peaks during business
    hours (9am-6pm) and dips overnight, to give CPU/network a realistic
    daily rhythm instead of flat random noise.
    """
    hours = timestamps.hour + timestamps.minute / 60.0
    # Shift so the peak of the sine wave lands around 1pm (13:00)
    radians = 2 * np.pi * (hours - 7) / 24
    wave = np.sin(radians)
    return 0.95 + 0.35 * wave  # ranges ~0.6 to ~1.3


def generate_baseline(server_id: str, timestamps: pd.DatetimeIndex, rng: np.random.Generator) -> pd.DataFrame:
    """
    Generate normal (non-anomalous) telemetry for one server, at any number of
    timestamps -- a full week (the batch generator) or a single instant (the live
    generator both call this the same way; only the length of `timestamps` differs.
    """
    n = len(timestamps)
    daily = diurnal_multiplier(timestamps)

    cpu = np.clip(30 * daily + rng.normal(0, 4, n), 2, 100)
    memory = np.clip(45 + rng.normal(0, 3, n), 5, 100)
    disk = np.clip(50 + rng.normal(0, 1, n), 5, 100)
    disk_io_read = np.clip(rng.normal(120, 20, n) * daily, 0, None)
    disk_io_write = np.clip(rng.normal(80, 15, n) * daily, 0, None)
    net_rx = np.clip(rng.normal(500_000, 80_000, n) * daily, 0, None)
    net_tx = np.clip(rng.normal(300_000, 60_000, n) * daily, 0, None)
    errors = rng.poisson(0.5, n)  # occasional background errors, near-zero baseline
    response_time = np.clip(rng.normal(120, 15, n), 20, None)

    return pd.DataFrame({
        "timestamp": timestamps,
        "server_id": server_id,
        "cpu_usage_percent": cpu,
        "memory_usage_percent": memory,
        "disk_usage_percent": disk,
        "disk_io_read": disk_io_read,
        "disk_io_write": disk_io_write,
        "network_rx_bytes": net_rx,
        "network_tx_bytes": net_tx,
        "application_error_count": errors,
        "response_time_ms": response_time,
        "is_injected_anomaly": 0,
    })


def derive_status(row) -> str:
    """Simple rule-based status label, independent of the ML model."""
    if row["cpu_usage_percent"] > 90 or row["memory_usage_percent"] > 90 or row["disk_usage_percent"] > 90:
        return "CRITICAL"
    if row["cpu_usage_percent"] > 75 or row["memory_usage_percent"] > 75 or row["application_error_count"] > 10:
        return "WARNING"
    return "OK"
